services:
  network-deploy-service:
    networks:
      - hemalbank

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: postgres:15
    healthcheck:
      test: pg_isready -U accounts
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "hemal1999"


  microservice-base-config:
    extends:
      service: network-deploy-service #any microservice will extend this service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: qa
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: hemal1999