spring:
  application:
    name: configserver
  profiles:
#    active: native
      active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
         git:
            uri: "https://github.com/HemalWiley/eazybytes-config.git"
            default-label: main
            timeout: 5
            clone-on-start: true
            force-pull: true
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
        enabled: true
    liveness-state:
        enabled: true
  endpoint:
    health:
      probes:
        enabled: true




encript:
  key: "45DSAERTYUIOPLKJHG8DS2CVBNM7890"

server:
  port: 8071
